name: Test and Deploy to Render

on:
  push:
    branches:
      - main  # Запускається при пуші в main
  pull_request:
    branches:
      - main  # Перевірка перед мерджем PR

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Використовуємо Python 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: run-tests  # Деплой запускається ТІЛЬКИ якщо всі тести пройшли

    steps:
      - name: Deploy via Render API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
               -H "Authorization: Bearer $RENDER_API_KEY" \
               -H "Content-Type: application/json" \
               --data '{}'
